apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app
  namespace: app-one
spec:
  destination:
    namespace: app-one
    server: https://kubernetes.default.svc
  project: app-one
  syncPolicy:
    automated: {}
  source:
    path: app
    repoURL: https://github.com/redhat-developer/openshift-gitops-getting-started
    targetRevision: HEAD
